latest updaterror TS2688: Cannot find type definition file for 'node'.   The file is in the program because:     Entry point of type library 'node' specified in compilerOptions tsconfig.json(5,29): error TS5107: Option 'moduleResolution=node10' is deprecated and will stop functioning in TypeScript 7.0. Specify compilerOption '"ignoreDeprecations": "6.0"' to silence this error.   Visit https://aka.ms/ts6 for migration information. tsconfig.json(7,9): error TS5101: Option 'baseUrl' is deprecated and will stop functioning in TypeScript 7.0. Specify compilerOption '"ignoreDeprecations": "6.0"' to silence this error.   Visit https://aka.ms/ts6 for migration information. ==> Build failed 😞e